const todoData = [
  {
    id: '1',
    title: 'Buy groceries',
    description: 'Buy essential groceries for the week.',
    dueDate: '2023-08-31',
    completed: false,
    priority: 'High',
    subtasks: ['Milk', 'Bread', 'Eggs'],
    progress: 10,
  },
  {
    id: '2',
    title: 'Finish project',
    description: 'Complete coding and finalize project documentation.',
    dueDate: '2023-09-15',
    completed: false,
    priority: 'Medium',
    subtasks: ['Code review', 'Documentation', 'Testing'],
    progress: 20,
  },
  {
    id: '3',
    title: 'Exercise',
    description: 'Engage in a 30-minute workout routine.',
    dueDate: '2023-08-25',
    completed: true,
    priority: 'Low',
    subtasks: ['Cardio', 'Strength training', 'Stretching'],
    progress: 30,
  },
  {
    id: '4',
    title: 'Read a book',
    description: 'Read at least one chapter of the book.',
    dueDate: '2023-09-05',
    completed: false,
    priority: 'High',
    subtasks: ['Chapter 1', 'Chapter 2', 'Chapter 3'],
    progress: 40,
  },

  {
    id: '5',
    title: 'Task 5',
    description: 'This is task number 5.',
    dueDate: '2023-08-20',
    completed: true,
    priority: 'Low',
    subtasks: ['Subtask 1', 'Subtask 2'],
    progress: 50,
  },
  {
    id: '6',
    title: 'Task 6',
    description: 'This is task number 6.',
    dueDate: '2023-08-21',
    completed: false,
    priority: 'Medium',
    subtasks: ['Subtask 1'],
    progress: 60,
  },
  {
    id: '7',
    title: 'Buy groceries',
    description: 'Buy essential groceries for the week.',
    dueDate: '2023-08-31',
    completed: false,
    priority: 'High',
    subtasks: ['Milk', 'Bread', 'Eggs'],
    progress: 70,
  },
  {
    id: '8',
    title: 'Finish project',
    description: 'Complete coding and finalize project documentation.',
    dueDate: '2023-09-15',
    completed: false,
    priority: 'Medium',
    subtasks: ['Code review', 'Documentation', 'Testing'],
    progress: 80,
  },
  {
    id: '9',
    title: 'Exercise',
    description: 'Engage in a 30-minute workout routine.',
    dueDate: '2023-08-25',
    completed: true,
    priority: 'Low',
    subtasks: ['Cardio', 'Strength training', 'Stretching'],
    progress: 90,
  },
  {
    id: '10',
    title: 'Read a book',
    description: 'Read at least one chapter of the book.',
    dueDate: '2023-09-05',
    completed: false,
    priority: 'High',
    subtasks: ['Chapter 1', 'Chapter 2', 'Chapter 3'],
    progress: 100,
  },

  {
    id: '11',
    title: 'Task 5',
    description: 'This is task number 5.',
    dueDate: '2023-08-20',
    completed: true,
    priority: 'Low',
    subtasks: ['Subtask 1', 'Subtask 2'],
    progress: 50,
  },
  {
    id: '12',
    title: 'Task 6',
    description: 'This is task number 6.',
    dueDate: '2023-08-21',
    completed: false,
    priority: 'Medium',
    subtasks: ['Subtask 1'],
    progress: 60,
  },
];

export default todoData;
